<script lang="ts">
  import { InputOTP } from "@kori-ui/svelte";

  let value = "892103";
</script>

<div class="flex flex-col items-center gap-4">
  <InputOTP
    {value}
    length={6}
    readonly
    separators={[3]}
    label="Pairing Code"
    description="This code is generated by the system and cannot be changed."
  />
</div>
